### ISSUE TITLE
Missing underscore in package.json dependencies

### ISSUE THREAD

**Issue by JonnyBGod** [ekalinin/sitemap.js#23]
module.js:338
    throw err;
    ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/joaoribeiro/Documents/Projects/cloudtasks.io/node_modules/sitemap/lib/utils.js:7:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by ekalinin** [comment]
Hi @JonnyBGod Thanks for report.
Yep, seems forgot to add that dependence into bower.json.

**Comment by JonnyBGod** [comment]
Not just that. You also have to change the package.json as you have the underscore dependency in "devDependencies" while this should be in "dependencies".

This make it work when you do `node install --production`
