### ISSUE TITLE
[ BUG ] EmptySitemap: You ended the stream without writing anything.

### ISSUE THREAD

**Issue by Amila-Rukshan** [ekalinin/sitemap.js#361]
**Describe the bug**
I got this error when starting my server which has sitemap as a dependency.

```
listening on 3000...
events.js:292
      throw er; // Unhandled 'error' event
      ^

EmptySitemap: You ended the stream without writing anything.
Emitted 'error' event on SitemapStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at SitemapStream.onerror (_stream_readable.js:752:7)
    at SitemapStream.emit (events.js:315:20)
    at done (_stream_transform.js:209:19)
    at _stream_transform.js:143:7
    at SitemapStream._flush (/Users/amilarukshansenadheera/Desktop/Projcts/heavenz-ssr/node_modules/sitemap/dist/lib/sitemap-stream.js:82:13)
    at SitemapStream.prefinish (_stream_transform.js:142:10)
    at SitemapStream.emit (events.js:315:20)
    at prefinish (_stream_writable.js:628:14)
    at finishMaybe (_stream_writable.js:636:5) 
```

**Expected behavior**
Should not give any errors

**Context:**
 - Library Version - 7.0.0

**Comment by derduher** [comment]
Hi. The error message there describes what the issue is. I’m not sure what you are looking for here.
